env:
  global:
    - CC_TEST_REPORTER_ID=17f8fadda4b2b6209c8e9f36441887cac12f0cfcb1a7896b805966a7b0b954e0

# Node setup
language: node_js
node_js:
  - '10'

# Chrome addon
addons:
  chrome: stable

# Docker service
sudo: required
services:
  - docker

# Caching
cache:
  directories:
    - node_modules

before_install:
  - npm i -g npm@6.3.0

before_script:
  - npm ci

script:
  - npm test

# Create coverage report and upload it to coveralls.io
after_success: npm run coverage
